[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.63.2",
    "requests>=2.32.3",
    "streamlit>=1.42.1",
    "twilio>=9.4.5",
]
